
name: Jekyll Themes
url: http://matt.harzewski.com
title: Abhishek's homepage
description: Bookmark this to keep an eye on my project updates!

permalink: /themes/:title/

plugins: [jekyll-paginate]

highlighter: pygments
paginate: 20

markdown: rdiscount
rdiscount:
    extensions: ['smart']
github:
  username: github_username # change to your GitHub username
