theme: "jekyll-theme-cayman-blog"
title: "Abhishek Hoempage"
description: "Bookmark this site for updates"

# About author
author:
  name: "Abhishek"
  bio: "I am me myself"
  avatar: "/assets/img/sample_avatar.jpg"

# Sidebar settings
sidebar:
  pinned_posts: true
  position: left

# Social links
social:
  twitter: "your_twitter_handle"
  github: "your_github_handle"
  linkedin: "your_linkedin_handle"

# Plugin settings
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
